name: Publish

on:
  release:
    types: [published]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/cowayger/osrm-valhalla-bridge:latest
          docker push ghcr.io/cowayger/osrm-valhalla-bridge:latest
